apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-sa-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: gcp-secret
    creationPolicy: Owner
  data:
  - secretKey: creds
    remoteRef:
      key: crossplane-sa-key