apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  name: test-port-vpc-subnet
  labels:
    composition: gke
spec:
  forProvider:
    ipCidrRange: 10.10.0.0/24
    networkSelector:
      matchLabels: 
        composition: gke
    region: us-west1