apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: google-kubernetes-cluster
  labels:
    provider: google
spec:
  compositeTypeRef:
    apiVersion: guga-api.com/v1alpha1
    kind: GKECluster
  resources:
  - name: nat
    base:
      apiVersion: compute.gcp.upbound.io/v1beta1
      kind: RouterNAT
      metadata:
        name: test-port-nat-router-config
        labels:
          composition: gke
      spec:
        forProvider:
          logConfig:
            - enable: true
              filter: ERRORS_ONLY
          natIpAllocateOption: AUTO_ONLY
          region: us-west1
          routerSelector:
            matchLabels:
              composition: gke
          sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
  - name: router
    base:
      apiVersion: compute.gcp.upbound.io/v1beta1
      kind: Router
      metadata:
        name: test-port-nat-router
        labels:
          composition: gke
      spec:
        forProvider:
          networkSelector:
            matchLabels: 
              composition: gke
          region: us-west1
  - name: subnet
    base:
      apiVersion: compute.gcp.upbound.io/v1beta1
      kind: Subnetwork
      metadata:
        name: test-port-vpc-subnet
        labels:
          composition: gke
      spec:
        forProvider:
          ipCidrRange: 10.10.0.0/24
          networkSelector:
            matchLabels: 
              composition: gke
          region: us-west1
  - name: vpc
    base:
      apiVersion: compute.gcp.upbound.io/v1beta1
      kind: Network
      metadata:
        name: test-port-vpc
        labels:
          composition: gke
      spec:
        forProvider:
          autoCreateSubnetworks: false
  - name: gke
    base:
      apiVersion: container.gcp.upbound.io/v1beta1
      kind: Cluster
      metadata:
        name: gke-crossplane-cluster
        labels:
          composition: gke
      spec:
        forProvider:
          initialNodeCount: 1
          removeDefaultNodePool: true
          location: us-west1-c
          networkSelector:
            matchLabels:
              composition: gke
          subnetworkSelector:
            matchLabels:
              composition: gke
          ipAllocationPolicy:
            - {}
  - name: nodepool
    base:
      apiVersion: container.gcp.upbound.io/v1beta1
      kind: NodePool
      metadata:
        name: gke-crossplane-np
        labels:
          composition: gke
      spec:
        forProvider: 
          clusterSelector:
            matchLabels:
              composition: gke
          location: us-west1-c
          nodeCount: 2
          nodeConfig:
            - machineType: e2-standard-2
              oauthScopes:
                - "https://www.googleapis.com/auth/logging.write"
                - "https://www.googleapis.com/auth/monitoring"
              labels:
                project: my-beautiful-cluster2
                creator: crossplane
              
              tags:
                - "gke-node"
                - "crossplane-managed"
              metadata:
                disable-legacy-endpoints: "true"
              diskSizeGb: 50
          networkConfig:
            - enablePrivateNodes: true