apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  name: gke-crossplane-np
  labels:
    composition: gke
spec:
  forProvider: 
    clusterRef:
      name: gke-crossplane-cluster
    location: us-west1-c
    nodeCount: 2
    nodeConfig:
      - machineType: e2-standard-2
        oauthScopes:
          - "https://www.googleapis.com/auth/logging.write"
          - "https://www.googleapis.com/auth/monitoring"
        labels:
          project: my-beautiful-cluster2
          creator: crossplane
        
        tags:
          - "gke-node"
          - "crossplane-managed"
        metadata:
          disable-legacy-endpoints: "true"
        diskSizeGb: 50
    networkConfig:
      - enablePrivateNodes: true